let lang = {
    "fr": {
        "textButtonRefreshMenu": "Rafraichir",
        "textButtonDestroyMenu": "Détruire",
        "textButtonLanguageMenu" : "Langue",
        "textConfirmationDestroyModal": "Confirmez-vous le piratage du système entier ?",
        "buttonCloseDestroyModal": "Non",
        "buttonConfirmDestroyModal": "Oui",
        "textConfirmationRefreshModal": "Confirmer-vous la réinitialisation du système entier ?",
        "buttonCloseRefreshModal": "Non",
        "buttonConfirmRefreshModal": "Oui",
        "textCarpetSettings": "Tapis",
        "textBlockCarpet": "Bloquer le tapis",
        "buttonCancelSettingsCarpet": "Annuler",
        "buttonApplySettingsCarpet": "Hacker",
        "textPiston1Settings": "Piston",
        "textBlockPiston1": "Bloquer le piston",
        "buttonCancelSettingsPiston1": "Annuler",
        "buttonApplySettingsPiston1": "Hacker",
        "textPiston2Settings": "Piston",
        "textBlockPiston2": "Bloquer le piston",
        "buttonCancelSettingsPiston2": "Annuler",
        "buttonApplySettingsPiston2": "Hacker",
        "textBarrierSettings": "Barrière",
        "textBlockBarrier": "Bloquer la barrière",
        "buttonCancelSettingsBarrier": "Annuler",
        "buttonApplySettingsBarrier": "Hacker",
        "Conveyor": "Tapis",
        "Piston": "Piston",
        "Barrier": "Barrière"
    },
    "en": {
        "textButtonRefreshMenu": "Refresh",
        "textButtonDestroyMenu": "Destroy",
        "textButtonLanguageMenu" : "Language",
        "textConfirmationDestroyModal": "Do you confirm the hacking of the entire system ?",
        "buttonCloseDestroyModal": "No",
        "buttonConfirmDestroyModal": "Yes",
        "textConfirmationRefreshModal": "Do you confirm the whole system reset ?",
        "buttonCloseRefreshModal": "No",
        "buttonConfirmRefreshModal": "Yes",
        "textCarpetSettings": "Conveyor",
        "textBlockCarpet": "Block the conveyor",
        "buttonCancelSettingsCarpet": "Cancel",
        "buttonApplySettingsCarpet": "Hack",
        "textPiston1Settings": "Piston",
        "textBlockPiston1": "Block the piston",
        "buttonCancelSettingsPiston1": "Cancel",
        "buttonApplySettingsPiston1": "Hack",
        "textPiston2Settings": "Piston",
        "textBlockPiston2": "Block the piston",
        "buttonCancelSettingsPiston2": "Cancel",
        "buttonApplySettingsPiston2": "Hack",
        "textBarrierSettings": "Barrier",
        "textBlockBarrier": "Block the barrier",
        "buttonCancelSettingsBarrier": "Cancel",
        "buttonApplySettingsBarrier": "Hack",
        "Conveyor": "Conveyor",
        "Piston": "Piston",
        "Barrier": "Barrier"
    },
    "de": {
        "textButtonRefreshMenu": "Aktualisierung",
        "textButtonDestroyMenu": "Zerstören",
        "textButtonLanguageMenu" : "Sprache",
        "textConfirmationDestroyModal": "Bestätigen Sie das Hacken des gesamten Systems?",
        "buttonCloseDestroyModal": "Nein",
        "buttonConfirmDestroyModal": "Ja",
        "textConfirmationRefreshModal": "Bestätigen Sie das Zurücksetzen des gesamten Systems?",
        "buttonCloseRefreshModal": "Nein",
        "buttonConfirmRefreshModal": "Ja",
        "textCarpetSettings": "Förderer",
        "textBlockCarpet": "Blockieren Sie das Förderband",
        "buttonCancelSettingsCarpet": "Stornieren",
        "buttonApplySettingsCarpet": "Piraten",
        "textPiston1Settings": "Kolben",
        "textBlockPiston1": "Kolben blockieren",
        "buttonCancelSettingsPiston1": "Stornieren",
        "buttonApplySettingsPiston1": "Piraten",
        "textPiston2Settings": "Kolben",
        "textBlockPiston2": "Kolben blockieren",
        "buttonCancelSettingsPiston2": "Stornieren",
        "buttonApplySettingsPiston2": "Piraten",
        "textBarrierSettings": "Barriere",
        "textBlockBarrier": "Blockieren Sie die Schranke",
        "buttonCancelSettingsBarrier": "Stornieren",
        "buttonApplySettingsBarrier": "Piraten",
        "Conveyor": "Förderer",
        "Piston": "Kolben",
        "Barrier": "Barriere"
    }
}